# Generated by Django 2.1.1 on 2018-09-20 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amortization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentOriginator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='investment',
            name='event',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='amortization.Event'),
        ),
        migrations.AddField(
            model_name='investment',
            name='projection',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='amortization.Projection'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investmentoriginator',
            name='investment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amortization.Investment'),
        ),
    ]
