# Generated by Django 2.1.1 on 2018-09-21 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amortization', '0002_auto_20180920_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('shortDescription', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='event',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='projection',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='investmentoriginator',
            name='investment',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='account',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='investment',
        ),
        migrations.RemoveField(
            model_name='projection',
            name='event',
        ),
    ]
