# Generated by Django 2.1.1 on 2018-09-22 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amortization', '0003_auto_20180921_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentoriginator',
            name='investment',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='amortization.Investment'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='investment',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='amortization.Investment'),
        ),
    ]
