# Generated by Django 2.1.1 on 2018-09-22 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amortization', '0004_auto_20180922_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='customer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='amortization.Customer'),
        ),
        migrations.AddField(
            model_name='investment',
            name='customer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='amortization.Customer'),
        ),
        migrations.AddField(
            model_name='investment',
            name='event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='amortization.Event'),
        ),
        migrations.AddField(
            model_name='investment',
            name='projection',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='amortization.Projection'),
        ),
        migrations.AddField(
            model_name='projection',
            name='event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='amortization.Event'),
        ),
        migrations.AlterField(
            model_name='investmentoriginator',
            name='investment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='amortization.Investment'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='investment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='amortization.Investment'),
        ),
    ]
