apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: medical-info-api-mn
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: medical-info-api-app
    spec:
      containers:
        - image: us.gcr.io/medicalinfoapi/medical_api-tomcat_v1:v1
          name: medical-info-api-con
          # Note:  The various names below are Docker container environment variables.
          env:
            - name: DB_HOST
              # Connect to the SQL proxy over the local network on a fixed port.
              # Change the [PORT] to the port number used by your database
              # (e.g. 3306).
              value: 127.0.0.1:3306
            # These secrets are required to start the pod.
            # [START cloudsql_secrets]
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: password
            # the medicalInfoAPI application is expecting 'root', Not sure.  Need better docs/example
            # the cloud proxy is expecting 'proxyuser'...
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: username
            # [END cloudsql_secrets]
          ports:
            - containerPort: 8080
              name: medicalinfo
        # Change [INSTANCE_CONNECTION_NAME] here to include your GCP --> medicalinfoapi:us-east1:medical-info 
        # project, the region of your Cloud SQL instance and the name
        # of your Cloud SQL instance. The format is
        # $PROJECT:$REGION:$INSTANCE
        # Insert the port number used by your database.
        # [START proxy_container]
        - image: gcr.io/cloudsql-docker/gce-proxy:1.09
          name: cloudsql-proxy
          command: ["/cloud_sql_proxy", "--dir=/cloudsql",
                    "-instances=medicalinfoapi:us-east1:medical-info=tcp:3306",
                    "-credential_file=/secrets/cloudsql/credentials.json"]
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
            - name: ssl-certs
              mountPath: /etc/ssl/certs
            - name: cloudsql
              mountPath: /cloudsql
        # [END proxy_container]
      # [START volumes]
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
        - name: ssl-certs
          hostPath:
            path: /etc/ssl/certs
        - name: cloudsql
          emptyDir:
# [END volumes]