use `moosewaredata`;

SET foreign_key_checks = 0;

drop table if exists PATIENT; 
CREATE TABLE PATIENT (PATIENTID INTEGER AUTO_INCREMENT NOT NULL, FAMILYNAME VARCHAR(255) NOT NULL, GIVENNAME VARCHAR(255) NOT NULL, EMRSYSTEM_EMRID INTEGER NOT NULL, PRIMARY KEY (PATIENTID))
ENGINE=INNODB;

drop table if exists EMRSYSTEM;
CREATE TABLE EMRSYSTEM (EMRID INTEGER AUTO_INCREMENT NOT NULL, BASEURL VARCHAR(255), EMRNAME VARCHAR(255), GETPATIENTALLERGYRESOURCE VARCHAR(255), GETPATIENTMEDICATIONSRESOURCE VARCHAR(255), GETPATIENTRESOURCE VARCHAR(255), PUTPATIENTALLERGYRESOURCE VARCHAR(255), PUTPATIENTMEDICATIONSRESOURCE VARCHAR(255), PUTPATIENTRESOURCE VARCHAR(255), PRIMARY KEY (EMRID))
ENGINE=INNODB;

drop table if exists MEDICALAREA;
CREATE TABLE MEDICALAREA (MEDICALAREAID INTEGER AUTO_INCREMENT NOT NULL, FLOOR VARCHAR(255) NOT NULL, LOCATION POLYGON not null, NAME VARCHAR(255) NOT NULL UNIQUE, SPATIAL INDEX(LOCATION), PRIMARY KEY (MEDICALAREAID))
ENGINE=INNODB;

drop table if exists MEDICALAREAOFUSE;
CREATE TABLE MEDICALAREAOFUSE (MEDICALAREAOFUSEID INTEGER AUTO_INCREMENT NOT NULL, MEDAREA_MEDICALAREAID INTEGER NOT NULL, PATIENT_PATIENTID INTEGER NOT NULL, REASONFORVISIT_REASONFORVISITID INTEGER NOT NULL, PRIMARY KEY (MEDICALAREAOFUSEID))
ENGINE=INNODB;

drop table if exists REASONFORVISIT;
CREATE TABLE REASONFORVISIT (REASONFORVISITID INTEGER AUTO_INCREMENT NOT NULL, REASONFORVISIT VARCHAR(255), PRIMARY KEY (REASONFORVISITID))
ENGINE=INNODB;

ALTER TABLE PATIENT ADD CONSTRAINT FK_PATIENT_EMRSYSTEM_EMRID FOREIGN KEY (EMRSYSTEM_EMRID) REFERENCES EMRSYSTEM (EMRID);
ALTER TABLE MEDICALAREAOFUSE ADD CONSTRAINT FK_MEDICALAREAOFUSE_MEDAREA_MEDICALAREAID FOREIGN KEY (MEDAREA_MEDICALAREAID) REFERENCES MEDICALAREA (MEDICALAREAID);
ALTER TABLE MEDICALAREAOFUSE ADD CONSTRAINT FK_MEDICALAREAOFUSE_PATIENT_PATIENTID FOREIGN KEY (PATIENT_PATIENTID) REFERENCES PATIENT (PATIENTID);
ALTER TABLE MEDICALAREAOFUSE ADD CONSTRAINT MEDICALAREAOFUSE_REASONFORVISIT_REASONFORVISITID FOREIGN KEY (REASONFORVISIT_REASONFORVISITID) REFERENCES REASONFORVISIT (REASONFORVISITID);

insert into REASONFORVISIT (REASONFORVISIT) values('checkup');
insert into REASONFORVISIT (REASONFORVISIT) values('surgery');
insert into REASONFORVISIT (REASONFORVISIT) values('lab work');

insert into EMRSYSTEM (BASEURL, EMRNAME) values('https://open-ic.epic.com/FHIR/api/FHIR/DSTU2/', 'Epic sandbox');

-- area's are loaded via KML files.  The following is a working example of a large area in antarcita.
SET @poly = GeomFromText('POLYGON((-74.0 44.0, -74.0 45.0, -75.0 45.0, -74.0 44.0))');
insert into MEDICALAREA (name, floor, location) values ('big', '1', @poly);
-- select name, floor from MEDICALAREA where contains(location, GeomFromText('POINT(-74.5 44.5)'));
--to seletct the coordinates from the database:
--select ST_AsText(LOCATION) from MEDICALAREA where MEDICALAREAID=6;
-- produces:  POLYGON((-74.38456416295396 44.93304277662406,-74.38448511235494 44.93298941180348,-74.38440631366197 44.93305068858879,-74.38447881785378 44.93310209494523,-74.38456416295396 44.93304277662406))

insert into PATIENT (GIVENNAME, FAMILYNAME, EMRSYSTEM_EMRID) values ('Jason', 'Argonaut', (select EMRID from EMRSYSTEM where EMRNAME='Epic sandbox'));
insert into PATIENT (FAMILYNAME, GIVENNAME, EMRSYSTEM_EMRID) values ('Jessica', 'Argonaut', (select EMRID from EMRSYSTEM where EMRNAME='Epic sandbox'));
insert into PATIENT (FAMILYNAME, GIVENNAME, EMRSYSTEM_EMRID) values ('Flapjacks', 'Ragsdale', (select EMRID from EMRSYSTEM where EMRNAME='Epic sandbox'));
insert into PATIENT (FAMILYNAME, GIVENNAME, EMRSYSTEM_EMRID) values ('Pancakes', 'Ragsdale', (select EMRID from EMRSYSTEM where EMRNAME='Epic sandbox'));
insert into PATIENT (FAMILYNAME, GIVENNAME, EMRSYSTEM_EMRID) values ('Ragsdale','Waffles', (select EMRID from EMRSYSTEM where EMRNAME='Epic sandbox'));
insert into PATIENT (FAMILYNAME, GIVENNAME, EMRSYSTEM_EMRID) values ('Bacon', 'Ragsdale', (select EMRID from EMRSYSTEM where EMRNAME='Epic sandbox'));
insert into PATIENT (FAMILYNAME, GIVENNAME, EMRSYSTEM_EMRID) values ('Emily', 'Williams', (select EMRID from EMRSYSTEM where EMRNAME='Epic sandbox'));
insert into PATIENT (FAMILYNAME, GIVENNAME, EMRSYSTEM_EMRID) values ('James', 'Kirk', (select EMRID from EMRSYSTEM where EMRNAME='Epic sandbox'));
